sudo: required
dist: trusty

services:
  - postgres

language: ruby

branches:
  only:
    - master

before_script:
  - bundle exec rake db:create db:schema:load

before_install:
  - sudo wget https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip -O /usr/local/bin/chromedriver
  - sudo chmod 777 /usr/local/bin/chromedriver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

env:
  - RAILS_ENV=test

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/.yarn-cache
    - $TRAVIS_BUILD_DIR/node_modules
    - $BUNDLE_PATH
    - vendor/bundle
script:
  - bundle exec rake

rvm:
  - 2.4.2

notifications:
    email: false

addons:
  postgresql: "9.4"
  chrome: stable
